on:
  pull_request:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        run: docker login -u ajv21 -p Jun21@2021 
      - name: build and publish alpine image
        id: docker_build_alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true 
          tags: |
            ajv21/github-release-resource:alpine-latest
      - name: build and publish ubuntu image
        id: docker_build_ubuntu
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true 
          tags: |
            ajv21/github-release-resource:ubuntu-latest
